version: "3.7"

services:
        redis:
                image: redis:latest
                ports: 
                        - 6379:6379

        model_server:
                build: ./model
                ports:
                        - 8000:8000
                depends_on:
                        - redis

        website_client:
                build: ./website
                ports:
                        - 8083:8083
                depends_on:
                        - redis 
                        - model_server

        
