version: "3.7"

services:
        redis:
                image: redis:latest
                ports: 
                        - 6379:6379

        celery_app:
                build: ./model/celery
                volumes:
                        - ./model/app:/usr/src/app
                working_dir: /usr/src/app
                command: celery worker -A celery_worker:celery_app -c 2 > log-worker.txt 2>&1

        model_server:
                build: ./model
                volumes:
                        - ./model/app:/usr/src/app
                ports:
                        - 8000:8000
                depends_on:
                        - redis

        website_client:
                build: ./website
                ports:
                        - 8083:8083
                depends_on:
                        - redis 
                        - model_server

        
